package com.mtg.notes.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF785900)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDF9E)
val onPrimaryContainerLight = Color(0xFF261A00)
val secondaryLight = Color(0xFF6B5D3F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF5E0BB)
val onSecondaryContainerLight = Color(0xFF241A04)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFBFF)
val onBackgroundLight = Color(0xFF1E1B16)
val surfaceLight = Color(0xFFFFFBFF)
val onSurfaceLight = Color(0xFF1E1B16)
val surfaceVariantLight = Color(0xFFEDE1CF)
val onSurfaceVariantLight = Color(0xFF4D4639)
val outlineLight = Color(0xFF7F7667)

val primaryDark = Color(0xFFF5BE48)
val onPrimaryDark = Color(0xFF3F2E00)
val primaryContainerDark = Color(0xFF5B4300)
val onPrimaryContainerDark = Color(0xFFFFDF9E)
val secondaryDark = Color(0xFFD8C4A0)
val onSecondaryDark = Color(0xFF3A2F15)
val secondaryContainerDark = Color(0xFF52452A)
val onSecondaryContainerDark = Color(0xFFF5E0BB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1E1B16)
val onBackgroundDark = Color(0xFFEAE1D9)
val surfaceDark = Color(0xFF1E1B16)
val onSurfaceDark = Color(0xFFEAE1D9)
val surfaceVariantDark = Color(0xFF4D4639)
val onSurfaceVariantDark = Color(0xFFD1C5B4)
val outlineDark = Color(0xFF9A8F80)